"""HTTP REST routes: Markdown download, session info."""

from __future__ import annotations

from datetime import date

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response

from .session import get_session

router = APIRouter(prefix="/api")

ARTIFACT_ORDER = [
    "evaluation",
    "refined_requirements",
    "business_summary",
    "personas_usecases",
    "dor",
    "technical_design",
    "safe_deliverables",
    "pi_planning",
    "raci_timeline",
    # gantt removed — timeline section dropped
]


def _build_markdown(session) -> str:
    lines = [
        f"# {session.project_name} — CTO Requirements Analysis",
        f"",
        f"*Generated by CTO Requirements Agent · {date.today()}*",
        f"*Model: {session.model}*",
        f"",
        "---",
        "",
    ]
    for artifact_id in ARTIFACT_ORDER:
        text = session.artifacts.get(artifact_id, "").strip()
        if text:
            lines.append(text)
            lines.append("")
            lines.append("---")
            lines.append("")
    return "\n".join(lines)


@router.get("/export/markdown")
async def export_markdown(session_id: str) -> Response:
    session = get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found or expired.")
    if not session.artifacts:
        raise HTTPException(status_code=202, detail="Artifacts not ready yet.")

    content = _build_markdown(session)
    filename = f"{session.project_name.replace(' ', '_')}_CTO_Analysis.md"
    return Response(
        content=content.encode("utf-8"),
        media_type="text/markdown",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/session/{session_id}")
async def session_info(session_id: str) -> dict:
    session = get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found.")
    return {
        "session_id": session.session_id,
        "phase": session.phase.value,
        "round": session.round,
        "model": session.model,
        "project_name": session.project_name,
        "artifacts_ready": list(session.artifacts.keys()),
        "pdf_ready": session.pdf_bytes is not None,
    }
